// AUTO GENERATED by tools/loadmeta.go
package services_test

import (
	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
	"github.com/softlayer/softlayer-go/services"
	"github.com/softlayer/softlayer-go/session/sessionfakes"
)   

var _ = Describe("Monitoring Tests", func() {
	var slsession *sessionfakes.FakeSLSession
	BeforeEach(func() {
		slsession = &sessionfakes.FakeSLSession{}
	})

	Context("Testing SoftLayer_Monitoring_Robot service", func() {
		var sl_service services.Monitoring_Robot
		BeforeEach(func() {
			sl_service = services.GetMonitoringRobotService(slsession)
		})


		Context("SoftLayer_Monitoring_Robot::checkConnection", func() {
			It("API Call Test", func() {

				_, err := sl_service.CheckConnection()

				Expect(err).To(Succeed())
				Expect(slsession.DoRequestCallCount()).To(Equal(1))
			})
		})

		Context("SoftLayer_Monitoring_Robot::getObject", func() {
			It("API Call Test", func() {

				_, err := sl_service.GetObject()

				Expect(err).To(Succeed())
				Expect(slsession.DoRequestCallCount()).To(Equal(1))
			})
		})

	})

})

